// staging/src/k8s.io/apimachinery/pkg/api/validate/field_comparison.go
package validate // Or your chosen package alias used in generated code

import (
	"context"
	// "strings" // No longer needed here

	"k8s.io/apimachinery/pkg/api/operation"
	"k8s.io/apimachinery/pkg/util/validation/field"
)

// FieldComparisonConditional acts as a simple wrapper. It executes the provided
// validationLogic function, which contains the complete conditional validation logic
// generated by the code generator for a +k8s:fieldComparison tag.
//
// Tstruct: The type of the struct being validated (passed as pointer).
func FieldComparisonConditional[Tstruct any](
	ctx context.Context,
	op operation.Operation,
	fldPath *field.Path, // Path to the *struct* being validated
	newObj, oldObj *Tstruct, // The struct instances (oldObj can be nil)
	// Single function containing the comparison, path logic, value fetch, and conditional validation/error
	validationLogic func(ctx context.Context, op operation.Operation, fldPath *field.Path, newObj, oldObj *Tstruct) field.ErrorList,
) field.ErrorList {
	// The generator creates the function that handles the nil check for newObj
	// if necessary within its generated comparison logic.
	// We simply execute the provided logic.
	return validationLogic(ctx, op, fldPath, newObj, oldObj)
}
