//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package fieldcomparison

import (
	context "context"
	fmt "fmt"

	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	field "k8s.io/apimachinery/pkg/util/validation/field"
	testscheme "k8s.io/code-generator/cmd/validation-gen/testscheme"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *testscheme.Scheme) error {
	scheme.AddValidationFunc((*ExampleStruct)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_ExampleStruct(ctx, op, nil /* fldPath */, obj.(*ExampleStruct), safe.Cast[*ExampleStruct](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	return nil
}

func Validate_ExampleStruct(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *ExampleStruct) (errs field.ErrorList) {
	// type ExampleStruct
	errs = append(errs, validate.FieldComparisonConditional(ctx, op, fldPath, obj, oldObj, func(ctx context.Context, op operation.Operation, fldPath *field.Path, newObj *ExampleStruct, oldObj *ExampleStruct) field.ErrorList {
		var errs field.ErrorList

		if newObj.MinI <= newObj.I {
			targetPath := fldPath.Child("b")

			var newTargetFieldValue *bool
			newTargetFieldValue = &newObj.B

			var oldTargetFieldValue *bool
			if oldObj != nil {
				oldTargetFieldValue = &oldObj.B
			}

			// Call payload validator
			errs = append(errs, validate.FixedResult(ctx, op, targetPath, newTargetFieldValue, oldTargetFieldValue)...)
		} else {
			// --- Comparison False: Generate Invalid Error ---
			errs = append(errs, field.Invalid(fldPath, newObj, fmt.Sprintf("comparison failed: minI <= i requires b to be valid")))
		}

		return errs
	})...)

	// field ExampleStruct.TypeMeta has no validation
	// field ExampleStruct.S has no validation
	// field ExampleStruct.I has no validation
	// field ExampleStruct.MinI has no validation
	// field ExampleStruct.B has no validation
	// field ExampleStruct.F has no validation
	return errs
}
