//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package fieldcomparison

import (
	context "context"
	fmt "fmt"
	time "time"

	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	field "k8s.io/apimachinery/pkg/util/validation/field"
	testscheme "k8s.io/code-generator/cmd/validation-gen/testscheme"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *testscheme.Scheme) error {
	scheme.AddValidationFunc((*ExampleStruct)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_ExampleStruct(ctx, op, nil /* fldPath */, obj.(*ExampleStruct), safe.Cast[*ExampleStruct](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	return nil
}

func Validate_ExampleStruct(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *ExampleStruct) (errs field.ErrorList) {
	// type ExampleStruct
	errs = append(errs, validate.FieldComparisonValidateField(ctx, op, fldPath, obj, oldObj, "EndTime", ">=", "StartTime", "Replicas", func(o *ExampleStruct) *time.Time { return o.EndTime }, func(o *ExampleStruct) *time.Time { return o.StartTime }, func(o *ExampleStruct) *int { return &o.Replicas }, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *int) field.ErrorList {
		return validate.Minimum(ctx, op, fldPath, obj, oldObj, 1)
	})...)
	errs = append(errs, validate.FieldComparisonValidateField(ctx, op, fldPath, obj, oldObj, "NestedStruct.EndTime", ">=", "NestedStruct.StartTime", "NestedStruct.Replicas", func(o *ExampleStruct) *time.Time { return o.NestedStruct.EndTime }, func(o *ExampleStruct) *time.Time { return o.NestedStruct.StartTime }, func(o *ExampleStruct) *int { return &o.NestedStruct.Replicas }, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *int) field.ErrorList {
		return validate.Minimum(ctx, op, fldPath, obj, oldObj, 1)
	})...)

	// field ExampleStruct.TypeMeta has no validation
	// field ExampleStruct.Replicas has no validation
	// field ExampleStruct.Selector has no validation
	// field ExampleStruct.StartTime has no validation
	// field ExampleStruct.EndTime has no validation
	// field ExampleStruct.Mode has no validation
	// field ExampleStruct.AdvancedSetting has no validation
	// field ExampleStruct.NestedStruct has no validation
	return errs
}
