//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package ifspecified

import (
	context "context"
	fmt "fmt"

	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	field "k8s.io/apimachinery/pkg/util/validation/field"
	testscheme "k8s.io/code-generator/cmd/validation-gen/testscheme"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *testscheme.Scheme) error {
	scheme.AddValidationFunc((*NestedStruct)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_NestedStruct(ctx, op, nil /* fldPath */, obj.(*NestedStruct), safe.Cast[*NestedStruct](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc((*PointerStruct)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_PointerStruct(ctx, op, nil /* fldPath */, obj.(*PointerStruct), safe.Cast[*PointerStruct](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc((*SimpleStruct)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_SimpleStruct(ctx, op, nil /* fldPath */, obj.(*SimpleStruct), safe.Cast[*SimpleStruct](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	scheme.AddValidationFunc((*TypedefStruct)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}, subresources ...string) field.ErrorList {
		if len(subresources) == 0 {
			return Validate_TypedefStruct(ctx, op, nil /* fldPath */, obj.(*TypedefStruct), safe.Cast[*TypedefStruct](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresources: %v", obj, subresources))}
	})
	return nil
}

func Validate_ChildStruct(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *ChildStruct) (errs field.ErrorList) {
	// type ChildStruct
	errs = append(errs, validate.IfSpecified(ctx, op, fldPath, obj, oldObj, "Active", "ChildName", func(o *ChildStruct) bool { return o.Active }, func(o *ChildStruct) string { return o.ChildName }, validate.DNSLabel)...)
	errs = append(errs, validate.IfSpecified(ctx, op, fldPath, obj, oldObj, "Active", "Priority", func(o *ChildStruct) bool { return o.Active }, func(o *ChildStruct) int { return o.Priority }, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *int) field.ErrorList {
		return validate.Minimum(ctx, op, fldPath, obj, oldObj, 1)
	})...)

	// field ChildStruct.Active has no validation
	// field ChildStruct.ChildName has no validation
	// field ChildStruct.Priority has no validation
	return errs
}

func Validate_NestedStruct(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *NestedStruct) (errs field.ErrorList) {
	// field NestedStruct.TypeMeta has no validation
	// field NestedStruct.ParentIP has no validation

	// field NestedStruct.Child
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *ChildStruct) (errs field.ErrorList) {
			errs = append(errs, Validate_ChildStruct(ctx, op, fldPath, obj, oldObj)...)
			return
		}(fldPath.Child("Child"), &obj.Child, safe.Field(oldObj, func(oldObj *NestedStruct) *ChildStruct { return &oldObj.Child }))...)

	return errs
}

func Validate_PointerStruct(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *PointerStruct) (errs field.ErrorList) {
	// type PointerStruct
	errs = append(errs, validate.IfSpecified(ctx, op, fldPath, obj, oldObj, "Dependency", "IPAddress", func(o *PointerStruct) *string { return o.Dependency }, func(o *PointerStruct) string { return o.IPAddress }, validate.IPSloppy)...)
	errs = append(errs, validate.IfSpecified(ctx, op, fldPath, obj, oldObj, "Dependency", "DNSName", func(o *PointerStruct) *string { return o.Dependency }, func(o *PointerStruct) *string { return o.DNSName }, validate.DNSLabel)...)

	// field PointerStruct.TypeMeta has no validation
	// field PointerStruct.Dependency has no validation
	// field PointerStruct.IPAddress has no validation
	// field PointerStruct.DNSName has no validation
	return errs
}

func Validate_SimpleStruct(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *SimpleStruct) (errs field.ErrorList) {
	// type SimpleStruct
	errs = append(errs, validate.IfSpecified(ctx, op, fldPath, obj, oldObj, "Dependency", "IPAddress", func(o *SimpleStruct) string { return o.Dependency }, func(o *SimpleStruct) string { return o.IPAddress }, validate.IPSloppy)...)
	errs = append(errs, validate.IfSpecified(ctx, op, fldPath, obj, oldObj, "Dependency", "DNSName", func(o *SimpleStruct) string { return o.Dependency }, func(o *SimpleStruct) string { return o.DNSName }, validate.DNSLabel)...)
	errs = append(errs, validate.IfSpecified(ctx, op, fldPath, obj, oldObj, "Dependency", "Count", func(o *SimpleStruct) string { return o.Dependency }, func(o *SimpleStruct) int { return o.Count }, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *int) field.ErrorList {
		return validate.Minimum(ctx, op, fldPath, obj, oldObj, 1)
	})...)

	// field SimpleStruct.TypeMeta has no validation
	// field SimpleStruct.Dependency has no validation
	// field SimpleStruct.IPAddress has no validation
	// field SimpleStruct.DNSName has no validation
	// field SimpleStruct.Count has no validation
	return errs
}

func Validate_TypedefStruct(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *TypedefStruct) (errs field.ErrorList) {
	// type TypedefStruct
	errs = append(errs, validate.IfSpecified(ctx, op, fldPath, obj, oldObj, "Enabled", "IPAddressType", func(o *TypedefStruct) bool { return o.Enabled }, func(o *TypedefStruct) IPAddress { return o.IPAddressType }, validate.IPSloppy)...)

	// field TypedefStruct.TypeMeta has no validation
	// field TypedefStruct.Enabled has no validation
	// field TypedefStruct.IPAddressType has no validation
	return errs
}
