//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package k8sip

import (
	context "context"
	fmt "fmt"

	equality "k8s.io/apimachinery/pkg/api/equality"
	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	field "k8s.io/apimachinery/pkg/util/validation/field"
	testscheme "k8s.io/code-generator/cmd/validation-gen/testscheme"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *testscheme.Scheme) error {
	// type Struct
	scheme.AddValidationFunc(
		(*Struct)(nil),
		func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
			switch op.Request.SubresourcePath() {
			case "/":
				return Validate_Struct(
					ctx, op, nil, /* fldPath */
					obj.(*Struct),
					safe.Cast[*Struct](oldObj))
			}
			return field.ErrorList{
				field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath())),
			}
		})
	return nil
}

// Validate_IPItem validates an instance of IPItem according
// to declarative validation rules in the API schema.
func Validate_IPItem(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *IPItem) (errs field.ErrorList) {

	{ // field IPItem.IP
		fn := func(
			fldPath *field.Path,
			obj, oldObj *string,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj) {
					return nil
				}
			}
			// call field-attached validations
			if e := validate.IP(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *IPItem) *string {
				return &oldObj.IP
			})
		errs = append(errs, fn(fldPath.Child("ip"), &obj.IP, oldVal, oldObj != nil)...)
	}

	// field IPItem.Name has no validation
	return errs
}

// Validate_IPStringType validates an instance of IPStringType according
// to declarative validation rules in the API schema.
func Validate_IPStringType(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *IPStringType) (errs field.ErrorList) {

	if e := validate.IP(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
		errs = append(errs, e...)
	}

	return errs
}

// Validate_Struct validates an instance of Struct according
// to declarative validation rules in the API schema.
func Validate_Struct(
	ctx context.Context, op operation.Operation, fldPath *field.Path,
	obj, oldObj *Struct) (errs field.ErrorList) {

	// field Struct.TypeMeta has no validation

	{ // field Struct.IPField
		fn := func(
			fldPath *field.Path,
			obj, oldObj *string,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj) {
					return nil
				}
			}
			// call field-attached validations
			if e := validate.IP(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *Struct) *string {
				return &oldObj.IPField
			})
		errs = append(errs, fn(fldPath.Child("ipField"), &obj.IPField, oldVal, oldObj != nil)...)
	}

	{ // field Struct.IPPtrField
		fn := func(
			fldPath *field.Path,
			obj, oldObj *string,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj) {
					return nil
				}
			}
			// call field-attached validations
			if e := validate.IP(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *Struct) *string {
				return oldObj.IPPtrField
			})
		errs = append(errs, fn(fldPath.Child("ipPtrField"), obj.IPPtrField, oldVal, oldObj != nil)...)
	}

	{ // field Struct.IPSet
		fn := func(
			fldPath *field.Path,
			obj, oldObj []string,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			if e := validate.EachSliceVal(ctx, op, fldPath, obj, oldObj, validate.DirectEqual, nil, validate.IP); len(e) != 0 {
				errs = append(errs, e...)
			}
			// lists with set semantics require unique values
			if e := validate.Unique(ctx, op, fldPath, obj, oldObj, validate.DirectEqual); len(e) != 0 {
				errs = append(errs, e...)
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *Struct) []string {
				return oldObj.IPSet
			})
		errs = append(errs, fn(fldPath.Child("ipSet"), obj.IPSet, oldVal, oldObj != nil)...)
	}

	{ // field Struct.IPItems
		fn := func(
			fldPath *field.Path,
			obj, oldObj []IPItem,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if equality.Semantic.DeepEqual(obj, oldObj) {
					return nil
				}
			}
			// call field-attached validations
			// lists with map semantics require unique keys
			if e := validate.Unique(ctx, op, fldPath, obj, oldObj,
				func(a IPItem, b IPItem) bool { return a.IP == b.IP }); len(e) != 0 {
				errs = append(errs, e...)
			}
			// iterate the list and call the type's validation function
			if e := validate.EachSliceVal(ctx, op, fldPath, obj, oldObj,
				func(a IPItem, b IPItem) bool { return a.IP == b.IP }, validate.DirectEqual, Validate_IPItem); len(e) != 0 {
				errs = append(errs, e...)
			}
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *Struct) []IPItem {
				return oldObj.IPItems
			})
		errs = append(errs, fn(fldPath.Child("ipItems"), obj.IPItems, oldVal, oldObj != nil)...)
	}

	{ // field Struct.IPTypedefField
		fn := func(
			fldPath *field.Path,
			obj, oldObj *IPStringType,
			oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update {
				if obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj) {
					return nil
				}
			}
			// call the type's validation function
			errs = append(errs, Validate_IPStringType(ctx, op, fldPath, obj, oldObj)...)
			return
		}
		oldVal := safe.Field(oldObj,
			func(oldObj *Struct) *IPStringType {
				return &oldObj.IPTypedefField
			})
		errs = append(errs, fn(fldPath.Child("ipTypedefField"), &obj.IPTypedefField, oldVal, oldObj != nil)...)
	}

	return errs
}
